repos:
- repo: https://github.com/charliermarsh/ruff-pre-commit
  rev: 'v0.0.262'
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]


- repo: https://github.com/psf/black
  rev: stable
  hooks:
    - id: black
      language_version: python3.9